line_length:
    warning: 150
    error: 200
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true

disabled_rules:
    - unused_optional_binding
    - trailing_whitespace

