name: 'Build test binaries'
description: 'Compiles App .ipa and Test Suite .app for a Test Plan'
inputs:
  client-id:
    description: 'OpenPass Client ID'
    required: true
  testplan:
    description: 'Xcode Test Plan name, specifying which test(s) to run'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set Client ID
      run: Development/scripts/set-client-id.sh "${INPUTS_CLIENT_ID}"
      shell: bash
      env:
        INPUTS_CLIENT_ID: ${{ inputs.client-id }}
 
    - name: Build and export .ipa
      run: |
        Development/scripts/build-export-ipa.sh
        mv build/OpenPassDevelopmentApp.ipa build/"${INPUTS_TESTPLAN}".ipa
      shell: bash
      env:
        INPUTS_TESTPLAN: ${{ inputs.testplan }}

    - name: Build Test Suite
      run: Development/scripts/build-browserstack-test-suite.sh "${INPUTS_TESTPLAN}"
      shell: bash
      env:
        INPUTS_TESTPLAN: ${{ inputs.testplan }}