name: Generate and Publish Documentation

on:
  pull_request:
    branches: [ main ]

  # this allows us to manually run this job
  workflow_dispatch:

jobs:

  # Lint Check
  compile-module:
    name: Compile Module
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run:  swift build --arch arm64 -Xswiftc -sdk -Xswiftc /Applications/Xcode_14.2.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk -Xswiftc -target -Xswiftc arm64-apple-ios13.0
        