name: Test Pull Requests

on:
  pull_request:
    branches: [ main ]

  # this allows us to manually run this job
  workflow_dispatch:

jobs:

  # Lint Check
  swift-lint-check:
    name: SwiftLint Check
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Lint code
        run: swiftlint lint --config .swiftlint.yml --reporter github-actions-logging

      - name: Build
        run: xcodebuild -scheme OpenPass -sdk iphonesimulator16.4 -destination "OS=16.4,name=iPhone 14"

      - name: Run unit tests
        run: xcodebuild test -scheme OpenPassTests -sdk iphonesimulator16.4 -destination "OS=16.4,name=iPhone 14"
