name: Test Pull Requests

on:
  pull_request:
    branches: [ main ]

  # this allows us to manually run this job
  workflow_dispatch:

# https://github.com/actions/runner-images/?tab=readme-ov-file#available-images
jobs:

  test-code-changes:
    name: Test Code Changes
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v4

      - name: Lint code
        run: swiftlint lint --config .swiftlint.yml --strict --reporter github-actions-logging

      - name: Build for iOS
        run: xcodebuild -scheme OpenPass -destination "generic/platform=iOS"
      
      - name: Build for tvOS
        run: xcodebuild -scheme OpenPass -destination "generic/platform=tvOS"

      - name: Run unit tests on iOS
        run: xcodebuild test -scheme OpenPassTests -sdk iphonesimulator16.2 -destination "OS=16.2,name=iPhone 14"

      - name: Run unit tests on tvOS
        run: xcodebuild test -scheme OpenPassTests -sdk appletvsimulator16.1 -destination "OS=16.1,name=Apple TV"

      - name: Lint pod spec
        run: pod lib lint --verbose
