name: Test Pull Requests

on:
  pull_request:
    branches: [ main ]

  # this allows us to manually run this job
  workflow_dispatch:

# https://github.com/actions/runner-images/?tab=readme-ov-file#available-images
jobs:

  test-code-changes:
    name: Test Code Changes
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: brew install swiftlint

      - name: Lint code
        run: swiftlint lint --config .swiftlint.yml --strict --reporter github-actions-logging

      - name: Select Xcode 15.3
        run: sudo xcode-select -s /Applications/Xcode_15.3.app

      - name: Build for iOS
        run: xcodebuild -scheme OpenPass -destination "generic/platform=iOS"
      
      - name: Build for tvOS
        run: xcodebuild -scheme OpenPass -destination "generic/platform=tvOS"

      - name: Run unit tests on iOS
        run: xcodebuild test -scheme OpenPass -sdk iphonesimulator17.4 -destination "OS=17.4,name=iPhone 15"

      - name: Run unit tests on tvOS
        run: xcodebuild test -scheme OpenPass -sdk appletvsimulator17.4 -destination "OS=17.4,name=Apple TV"

      - name: Lint pod spec
        run: pod lib lint --verbose
