name: Test Pull Requests

on:
  pull_request:
    branches: [ main ]

  # this allows us to manually run this job
  workflow_dispatch:

jobs:

  test-code-changes:
    name: Test Code Changes
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Lint code
        run: swiftlint lint --config .swiftlint.yml --strict --reporter github-actions-logging

      - name: Build for iOS
        run: xcodebuild -scheme OpenPass -destination "generic/platform=iOS"
      
      - name: Build for tvOS
        run: xcodebuild -scheme OpenPass -destination "generic/platform=tvOS"

      - name: Run unit tests
        run: xcodebuild test -scheme OpenPassTests -sdk iphonesimulator16.2 -destination "OS=16.2,name=iPhone 14"
