name: Trigger iOS SDK Docs Generation

on:
  push:
    branches: [ main ]

  # this allows us to manually run this job
  workflow_dispatch:

jobs:

  trigger-ios-sdk-api-docs-generation:
    name: Trigger Generate iOS Docs Event
    runs-on: macos-latest

    steps:

      - name: Dispatch repository event to openpass-docs repo
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.OPENAPI_SPEC_UPDATED_TRIGGER_PAT }}
          repository: openpass-sso/openpass-docs
          event-type: ios-sdk-docs-updated
          client-payload: '{ "github_sha": "${{ github.sha }}" }'